---
sidebar: true
---

### Peer Reviewed Journal Articles

**Polzin, S.**, Lusk, J. L., & Wahdat, A. Z. (2023). Measuring Sustainable Consumer Food Purchasing and Behavior. *Appetite, 180*, 106369.

### Manuscripts in Progress

Dowd, C., **Polzin, S.**, Gleason, K., Yang, R., Narang, P., & Patel, R. (under review). Conflict's Impacts on Food Systems: Mapping Available Evidence of Interactions.

Wahdat, A. & **Polzin, S.** (under review). From Disasters to Hunger: Investigating the Causal Effect of Natural Disasters on Household Food Insufficiency in the US.

### Reports

Patel, R., Gleason, K., **Polzin, S.**, Ripamonti, D., Garvey, A., & Dowd, C. (2023). Conflict and Food Systems - Synthesis Report. *Concern Worldwide*.

Patel, R., Gleason, K., **Polzin, S.**, Ripamonti, D., Garvey, A., & Dowd, C. (2023) Conflict and Food Systems - Somalia Report. *Concern Worldwide.*

Patel, R., Gleason, K., **Polzin, S.**, Ripamonti, D., Garvey, A., & Dowd, C. (2023) Conflict and Food Systems - Haiti Report. *Concern Worldwide.*

Patel, R., Gleason, K., **Polzin, S.**, Ripamonti, D., Garvey, A., & Dowd, C. (2023) Conflict and Food Systems - Sudan Report. *Concern Worldwide*.

Lusk, J. L. & **Polzin, S.** (2022-23). Consumer Food Insights, Vol. 1-2. *Center for Food Demand Analysis and Sustainability, College of Agriculture, Purdue University*.

Fitzpatrick, M., Spears, K., Ryan, J., **Polzin, S.**, Gottlieb, G., & Maxwell, D. (2021). Making the Nexus Real: Moving from theory to practice. *Feinstein International Center, Tufts University*.

**Polzin, S.** & Codur, A.-M. (2021). Farmers as Ecosystem Regenerators: Reimagining agriculture with the Northeast Healthy Soil Network. *Global Development And Environment Institute, Tufts University*. Policy Brief No. 14.

**Polzin, S.** (2020). Soil Carbon, Water Management, and Natural Infrastructure: Building resilient watersheds in the Northeastern United States. *Global Development And Environment Institute, Tufts University*. Policy Brief No. 12.

### Popular Press

**Polzin, S.** & Lusk, J. (2023). Inflation hasn't increased US food insecurity overall, according to our new tracker. *The Conversation*.

**Polzin, S.**, Wahdat, A. Z., & Lusk, J. (2022). Why food insecurity among Gen Z is so much higher than for other age groups. *The Conversation*.
